# Generated by Django 4.0.3 on 2022-05-02 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Категория', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Название', max_length=50)),
                ('prev_img', models.ImageField(upload_to='articles_img')),
                ('subtitle', models.CharField(default='Под заголовок', max_length=50)),
                ('authors', models.CharField(default='Участники создания статьи', max_length=50)),
                ('edit_data', models.DateTimeField(auto_now=True)),
                ('pub_data', models.DateTimeField(verbose_name='date published')),
                ('content', models.TextField(default='Текст статьи')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='article.category')),
            ],
        ),
    ]
